/**
 * Webform importer — turns the HTML Zoho generates into live site config.
 *
 * Zoho CRM exposes no API to create or read a webform (File 15). The generated
 * HTML is the ONLY carrier of three values plus the LEADCF field mapping, and
 * the LEADCF indices cannot be derived: field metadata exposes only api_name and
 * id (verified 2026-08-13).
 *
 * So the founder's single action is "create the webform, copy the HTML". This
 * script does everything after that — no manual mapping, no hand-edited config.
 *
 *   node scripts/import-webform.mjs path/to/pasted-webform.html
 *
 * Writes:
 *   - website/src/data/site.json          (action URL + xnQsjsdp + xmIwtLD)
 *   - website/src/data/webform-fields.json (LEADCF name -> CRM field label)
 * Zero dependencies (ADR-002). ADR-003 unchanged: the browser still POSTs
 * directly to Zoho; this only records where.
 */

import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const src = process.argv[2];
if (!src) {
  console.error("✗ usage: node scripts/import-webform.mjs <pasted-webform.html>");
  process.exit(1);
}

const html = await readFile(src, "utf8");

// Zoho renders attributes as `name = 'x' value = 'y'` — with spaces around the
// equals sign and single quotes. Tolerate both styles; a stricter regex silently
// found nothing against the real generated form.
const EQ = "\\s*=\\s*";
const Q = "[\"']";
const attr = (name) => {
  const m = html.match(new RegExp(`name${EQ}${Q}${name}${Q}[^>]*?value${EQ}${Q}([^"']*)${Q}`, "i"))
    || html.match(new RegExp(`value${EQ}${Q}([^"']*)${Q}[^>]*?name${EQ}${Q}${name}${Q}`, "i"));
  return m?.[1] ?? null;
};

const action = html.match(new RegExp(`<form[^>]*?\\saction${EQ}${Q}([^"']+)${Q}`, "i"))?.[1] ?? null;
const key = attr("xnQsjsdp");
const digest = attr("xmIwtLD");

const missing = Object.entries({ action, xnQsjsdp: key, xmIwtLD: digest })
  .filter(([, v]) => !v)
  .map(([k]) => k);
if (missing.length) {
  console.error(`✗ import-webform: could not find ${missing.join(", ")} in ${src}.`);
  console.error("  Paste the COMPLETE generated form, including its hidden inputs.");
  process.exit(1);
}

// LEADCF mapping. Zoho renders each custom field as <label for="LEADCFn">Label</label>
// next to its input; fall back to the input's own id/name when no label is present.
const mapping = {};
for (const m of html.matchAll(new RegExp(`<label[^>]*?for${EQ}${Q}(LEADCF\\d+)${Q}[^>]*>([\\s\\S]*?)</label>`, "gi"))) {
  mapping[m[1]] = m[2].replace(/<[^>]*>/g, "").replace(/\s+/g, " ").replace(/\*+$/, "").trim();
}
for (const m of html.matchAll(new RegExp(`name${EQ}${Q}(LEADCF\\d+)${Q}`, "gi"))) {
  if (!(m[1] in mapping)) mapping[m[1]] = null; // present but unlabelled
}

const sitePath = path.join(ROOT, "website", "src", "data", "site.json");
const site = JSON.parse(await readFile(sitePath, "utf8"));
site.zoho_webform_action = action;
site.zoho_webform_key = key;
site.zoho_webform_digest = digest;
delete site._zoho_webform_note;
await writeFile(sitePath, JSON.stringify(site, null, 2) + "\n");

await writeFile(
  path.join(ROOT, "website", "src", "data", "webform-fields.json"),
  JSON.stringify(
    {
      _comment:
        "GENERATED by scripts/import-webform.mjs from the Zoho-generated webform HTML. " +
        "Maps Zoho's LEADCF input names to the CRM field they carry. Zoho assigns these " +
        "indices at generation time; they cannot be derived from the API (File 15).",
      _imported: new Date().toISOString().slice(0, 10),
      fields: mapping,
    },
    null,
    2
  ) + "\n"
);

const labelled = Object.values(mapping).filter(Boolean).length;
console.log(
  `✓ import-webform: action + xnQsjsdp + xmIwtLD written to site.json; ` +
    `${Object.keys(mapping).length} LEADCF field(s) mapped (${labelled} labelled)`
);
